version = 0.1
[default.deploy.parameters]
stack_name = "OceanData"
resolve_s3 = true
s3_prefix = "tiki-sam/ocean/data"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
