AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ocean - Data Infrastructure

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ocean-data
      CodeUri: ..
      Handler: com.mytiki.ocean.data.App::handleRequest
      Runtime: java17
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 20
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 10
            Queue: !GetAtt Queue.Arn

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ocean-data

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: ocean-data
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt Queue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: "arn:aws:s3:::mytiki-ingest"
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      Queues:
        - !Ref Queue

Outputs:
  Function:
    Description: "ARN"
    Value: !GetAtt Function.Arn
  Queue:
    Description: "ARN"
    Value: !GetAtt Queue.Arn
