version = 0.1

[default.global.parameters]
stack_name = "ocean-data-aws"
s3_bucket = "mytiki-sam-deploy"
s3_prefix = "ocean/data/aws"
region = "us-east-2"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [
    "CAPABILITY_IAM",
    "CAPABILITY_AUTO_EXPAND"
]
image_repositories = []
parameter_overrides = [
    "SourceBucket=mytiki-ingest",
    "MetadataQueue=ocean-catalog.fifo",
    "IngestQueue=arn:aws:sqs:us-east-2:254962200554:ocean-catalog.fifo",
    "TableName=logs"
]
